steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-app:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nginx-app:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=ggai'
substitutions:
  _COMMIT_SHA: $(COMMIT_SHA)


images:
- 'gcr.io/$PROJECT_ID/nginx-app:$COMMIT_SHA'

logsBucket: gs://ggai-zulip
